theme: jekyll-theme-modernist
markdown: kramdown
title: CCiC8 - Conference of China iGEMer Community
url: https://ccic8.site

redirects: yes

collections:
  posts:
    output: true
    permalink: /:title/
  volunteers:
    output: true
    permalink: /:title