theme: jekyll-theme-modernist
title: CCiC8 - Conference of China iGEMer Community
google_analytics: UA-30563986-1
backup_team_title: a team

collections:
  posts:
    output: true
    permalink: /:title/