theme: jekyll-theme-modernist
markdown: kramdown
title: CCiC8 - Conference of China iGEMer Community
url: https://ccic8.site
google_analytics: UA-30563986-1

collections:
  posts:
    output: true
    permalink: /:title/